### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by KevinWorkman** [Priya411/CodeUGroup3#25]
This is Google's favorite question: what if you had a billion users?

There are several places in the code that loop through every message or every conversation or every user. If you had a billion users, this would get pretty slow. Maybe think about how you'd improve performance?

Usually this involves storing stuff in a Map instead of a List, but there are plenty of other data structures that might come in handy as well.

**Comment by TheMkrage** [comment]
Implementing Hashmap feature discussed in call. The hashmap can also be used for changing a user's control level (member, owner, creator). Will probably store hashmap in View and write some methods to interface with it.

**Comment by TheMkrage** [comment]
Implemented using model stores to avoid looping everytime
